# Generated by Django 4.2.6 on 2023-10-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countdown', '0003_alter_repeatableevent_event_day_of_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repeatableevent',
            name='event_day_of_week',
            field=models.CharField(blank=True, choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('0', 'Sunday')], max_length=20),
        ),
    ]
