# Generated by Django 4.2.6 on 2023-10-12 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countdown', '0004_alter_repeatableevent_event_day_of_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repeatableevent',
            name='repeat_event_each_days',
        ),
    ]
